### ISSUE TITLE
LFS data quota exceeded

### ISSUE THREAD

**Issue by SludgePhD** [webonnx/wonnx#103]
It looks like the LFS quota has been exceeded, so only the AWS-hosted `data.zip` can currently be used to get the data files:

```
$ git lfs fetch origin
fetch: Fetching reference refs/heads/wgpu-backend-default
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                                                                                                                                            
error: failed to fetch some objects from 'https://github.com/webonnx/wonnx.git/info/lfs'
```

I see that `opt-mnist.onnx` and `single_relu.onnx` are only kilobytes/bytes, and `opt-squeeze.onnx` is only a few MB. Is LFS really necessary for so little data?

**Comment by haixuanTao** [comment]
The idea is that we might want to add other models and maybe other data for testing.

But ultimately, we should probably remove git lfs.

**Comment by pixelspark** [comment]
I got fed up with this and moved the models to the repository itself without LFS. This shouldn't be too much of an issue as it's just a few MB and unlikely to be changed.
