### ISSUE TITLE
CLI cannot deserialize models

### ISSUE THREAD

**Issue by sonovice** [webonnx/wonnx#126]
**Describe the bug**
The CLI tool cannot deserialize models from this repository. It panics with the following msg:
```
> RUST_BACKTRACE=1 nnx info ./data/models/opt-squeeze.onnx

thread 'main' panicked at 'Could not deserialize the model: WireError(IncorrectTag(118))', wonnx-cli/src/main.rs:47:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/878aef79dcdf59d19bb8482202dc55e58ceb62ff/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/878aef79dcdf59d19bb8482202dc55e58ceb62ff/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/878aef79dcdf59d19bb8482202dc55e58ceb62ff/library/core/src/result.rs:1814:5
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: nnx::main
```

**To Reproduce**
1. clone repo
2. `cd` into cloned dir
3. install wonnx-cli via `cargo install --git https://github.com/webonnx/wonnx.git wonnx-cli`
4. execute `nnx info ./data/models/opt-squeeze.onnx`

**Expected behavior**
The CLI should load the model and show some information.

**Desktop (please complete the following information):**
 - OS: Linux on Kernel 5.19.0
 - GPU: NVIDIA GeForce RTX 3090

**Comment by haixuanTao** [comment]
I think that your using the git-lfs tag of the model and not the real data. You should try to download the data is either via git LFS or the link in the Readme. I agree that it is confusing.

**Comment by pixelspark** [comment]
Not sure if it is in the documentation, but here's an example for converting certain parametric dimensions to fixed ones (in this case for a BertSQuaD model) using onnxsimplifier:

````sh
python -m onnxsim ./bertsquad-12.onnx ./bertsquad-12-inferred.onnx --input-shape "unique_ids_raw_output___9:0:1" "segment_ids:0:1,256" "input_mask:0:1,256" "input_ids:0:1,256"
````
