### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by antimora** [webonnx/wonnx#149]
In the cargo.toml files, I find that the license is "MIT OR Apache-2.0". However, only a copy of MIT license checked in at the root. 

We would very much prefer if the code is open sourced under the dual license. We are excited about your work and would like to bring some parts to our young project for [burn](https://github.com/burn-rs/burn) wgpu backend. Burn is opened source under MIT and Apache-2.0 and would be easy to port some of your code. We will comply with copyright rules and noticed as required.

**Comment by pixelspark** [comment]
We should definitely clarify the license situation! Personally I am in favour of dual-licensing (MIT OR Apache-2.0). Pull request #150 contains the necessary changes, and is awaiting approval from all involved contributors.
