### ISSUE TITLE
Issues with GEMM

### ISSUE THREAD

**Issue by satyajitghana** [webonnx/wonnx#176]
Issues with loading a simple FC layers Model

```
SessionError {ptr: 1638408} "IR error: issue with data types: encountered parametrized dimensions 'Gemmoutput_dim_0'; this is not currently supported (this may be solved by running onnx-simplifier on the model first)"
```

Attached mnist.onnx and mnist.script.pt

[mnist.zip](https://github.com/webonnx/wonnx/files/12098121/mnist.zip)

I've tried running onnx-simplifier on it, doesn't do anything.

**Comment by pixelspark** [comment]
Well, wonnx doesn't support parametrized dimensions: you need to explicitly specify shapes up front. `onnx-simplifier` will not do this by default, but has options to specify the missing dimension parameters, and will then fill them in for you.

**Comment by pixelspark** [comment]
Also (see README) the `nnx prepare` command supports setting parametrized dimensions:

````
To specify dynamic dimension parameters, add e.g. --set batch_size=1.
`````

It may or may not work in your case because not all op types are supported currently.
