### ISSUE TITLE
Support for ONNX scaler datatype `bool`

### ISSUE THREAD

**Issue by mush42** [webonnx/wonnx#184]
**Describe the bug**

Many of the models that I try to run fail with the following message:

```bash
$nnx infer model.onnx
Error: backend execution error: IR error: issue with data types: the ONNX scalar data type 'BOOL' is not supported
```

## Expected behavior

I should be able to run the model without issues.

**Comment by pixelspark** [comment]
As the error states: WONNX does not support the 'bool' value type just yet. You may want to have a look at the model's nodes (using e.g. Netron) to see where and how it uses bools. In most cases there is only minimal usage and it may be possible to replace it.
