### ISSUE TITLE
Logo in README Not Best For GitHub Dark Theme

### ISSUE THREAD

**Issue by zicklag** [webonnx/wonnx#36]
Hey there, I just noticed that the logo doesn't look quite right on the GitHub dark theme.

Not sure what the best path forward is, but jus thought I'd let you know in case you don't notice it because you're on the light theme.

![image](https://user-images.githubusercontent.com/25393315/149012857-fd50fb1f-b49a-4121-a654-ac8892d997ab.png)

Neat looking project BTW! :+1:

**Comment by haixuanTao** [comment]
Thanks! Yeah, ahah, I did it really quickly, I should probably do another header. 

Thanks for the issue :)

**Comment by pixelspark** [comment]
Hi,

I tweaked the logo a bit (a square 'avatar' for the org as well as a logo with slogan that works a bit better on black backgrounds). Inkscape SVG attached. If you like it I will update the logos. Should use SVG's anyway of course.

![wonnx](https://user-images.githubusercontent.com/181337/153184132-e43372f1-3c88-40f5-9f4f-1596f7491c66.svg)


![rect13547](https://user-images.githubusercontent.com/181337/153176556-ca76f868-6e9d-4f8c-997f-b336c09831e4.png)
![rect13842](https://user-images.githubusercontent.com/181337/153176564-16ba7cee-7984-434a-9ca1-9b54bedcbf73.png)

**Comment by haixuanTao** [comment]
![Screenshot from 2022-02-09 14-30-41](https://user-images.githubusercontent.com/22787340/153211137-f68fab3d-05b9-4db0-8b19-2299d92bd2ab.png)


I'm all in to have svgs but the formating of the SVG you put looks weird on my laptop

**Comment by pixelspark** [comment]
> This looks much better.
> 
> I think it would be perfect if it could render well in dark mode as well. ![Screenshot from 2022-02-09 14-50-00](https://user-images.githubusercontent.com/22787340/153214454-8cd3680a-ce99-454f-b3d8-bcfc76a1d5b9.png)
> 
> But if you don't want to bother feel free to update the settings and commit the new logo.

I specifically added the white outline so it looks a little better than the old logo,but I agree it is not yet optimal. 

With some SVG tricks you could probably make it dynamic (if the browser supports the CSS 'prefers-color-scheme' mechanism? Not sure how wide-spread/compatible that is).

**Comment by pixelspark** [comment]
Here's one that should automatically switch to white text when dark mode is enabled!
![wonnx_slogan_opt](https://user-images.githubusercontent.com/181337/153217394-45a54747-c829-4e63-92da-041d8a19b449.svg)

**Comment by haixuanTao** [comment]
![Screenshot from 2022-02-09 15-11-39](https://user-images.githubusercontent.com/22787340/153218252-52cfd696-724b-42b1-b5f0-32db00eaeddf.png)

The dark version is perfect and the light version seems great when I click on the SVG. But when it is within a comment the SVG looks weird, not sure why. 

![Screenshot from 2022-02-09 15-11-39](https://user-images.githubusercontent.com/22787340/153218733-eee19d7f-2d27-4499-8e95-52b8a9ada70c.png)

I think that you can try to put it in the README and preview how it render.

**Comment by pixelspark** [comment]
Yes, there's something funny going on with caching I suspect. Will commit this image to the repo later today (I already updated the org's logo and social image).
