### ISSUE TITLE
graph info shape is empty

### ISSUE THREAD

**Issue by zimond** [webonnx/wonnx#66]
**Describe the bug**
create a graph with a info node with any op, in wgsl the `i_shape[n]` global variable is empty

**reproduce**
- in `conv.wgsl` add a line `let _ = {{i_shape[1][1]}}` which evaluates to index the dim of weight,
- run test `conv_without_pad`
- test crash

**Comment by pixelspark** [comment]
Hm, this is likely an error in `wonnx::utils::graph` which is a function that allows you to construct an ONNX graph declaratively. It is typically only used to write tests. While the dimensions for `W` are provided they are probably not inserted in the right places in the resulting ONNX model structures. Probably easy to fix (just have to check where wonnx is reading the dimension info from in this case - it can come from various places!).

**Comment by pixelspark** [comment]
See #78
