### ISSUE TITLE
Sequence seems extremely slow

### ISSUE THREAD

**Issue by zimond** [webonnx/wonnx#72]
**Describe the bug**
I have a model with 159 nodes, and wonnx log claims to have sequenced 220 tensors. And the whole sequence procedure takes up to 230s (!!) on my M1 macbook. 

**Expected behavior**
The whole sequencing step should be done in a bearable time

**Desktop**
 - OS: Macos
 - Model: M1

**Comment by pixelspark** [comment]
Hm, that shouldn't happen, nodes should be visited and processed exactly once (there are a few exceptions where we coalesce several nodes into one, but initializer tensors should never be 'uploaded' more than once, as that would also cause excessive GPU memory usage!). 

Could you provide us with a test case so we can reproduce? (i.e. a small ONNX file that exhibits this behaviour).

**Comment by zimond** [comment]
I read the sequencer's code, it seems that currently you are recursively visiting node input source node and run sequence on the source nodes. So if node A outputs two tensor as inputs of B and C respectively, sequencer currently will visit A twice ( from b.input.source_node & c.input.source_node).

Add a third param like `node_reg: HashSet<NodeIdentifier>` and insert node identifier everytime a node is visited, the model creation time drastically reduced to 230ms

**Comment by pixelspark** [comment]
> I read the sequencer's code, it seems that currently you are recursively visiting node input source node and run sequence on the source nodes. So if node A outputs two tensor as inputs of B and C respectively, sequencer currently will visit A twice ( from b.input.source_node & c.input.source_node).
> 
> Add a third param like `node_reg: HashSet<NodeIdentifier>` and insert node identifier everytime a node is visited, the model creation time drastically reduced to 230ms

Thanks for digging into this! Could you submit this as PR perhaps?
