### ISSUE TITLE
MaxPool op is not correct

### ISSUE THREAD

**Issue by zimond** [webonnx/wonnx#75]
**Describe the bug**
I think Maxpool is not implemented correctly, given there's no test against MaxPool now, here's one adopted from onnx test suite:

```rust

#[test]
pub fn test_maxpool() {
    let mut input_data = HashMap::new();

    let data: Vec<f32> = (1..=25).map(|x| x as f32).collect();
    let shape = vec![1, 1, 5, 5];
    input_data.insert("X".to_string(), data.as_slice().into());

    let conv_model = model(graph(
        vec![tensor("X", &shape)],
        vec![tensor("Y", &[1, 1, 2, 2])],
        vec![],
        vec![],
        vec![node(
            vec!["X"],
            vec!["Y"],
            "max_pool",
            "MaxPool",
            vec![
                attribute("kernel_shape", vec![2, 2]),
                attribute("strides", vec![2, 2]),
            ],
        )],
    ));

    let session =
        pollster::block_on(wonnx::Session::from_model(conv_model)).expect("Session did not create");
    let result = pollster::block_on(session.run(&input_data)).unwrap();
    assert_eq!(result["Y"], [7.0, 9.0, 17.0, 19.0]);
}
```

Adopted from [here](https://github.com/onnx/onnx/blob/main/onnx/backend/test/case/node/maxpool.py#L111)

wonnx outputs `[7.0, 0.0, 0.0, 0.0]`, which should be `[7.0, 9.0, 17.0, 19.0]`

**Comment by zimond** [comment]
Could you add a fix to this? My model is yield wrong result. Maybe I could test if this is the reason

**Comment by haixuanTao** [comment]
So, I've added a small template #76  that pass your test but there is still issues with maxpool so don' t take it for granted.

**Comment by zimond** [comment]
Yeah... Thanks for the quick fix. And as expected, my model is stilling not running correctly. Maybe there's more issues to be found. I will take some further investigation.
