### ISSUE TITLE
Conv with bias is not correct

### ISSUE THREAD

**Issue by zimond** [webonnx/wonnx#79]
After several days of debugging I think I finally get why wonnx is giving incorrect results. It seems that conv  is not calculating bias correctly.

Test:
```rust

#[test]
fn conv_bias() {
    let n = 5;
    let c = 1;
    let mut input_data = HashMap::new();

    let data: Vec<f32> = (0..25).map(|x| x as f32).collect();
    let shape = vec![1, c as i64, n as i64, n as i64];
    input_data.insert("X".to_string(), data.as_slice().into());

    let kernel_n = 3;
    let m = 1;
    let data_w: Vec<f32> = (0..18).map(|_| 1.0f32).collect();
    let data_b = vec![0.0, 0.0];
    let conv_model = model(graph(
        vec![tensor("X", &shape)],
        vec![tensor("Y", &[1, 2, 5, 5])],
        vec![tensor("W", &[2, c, 3, 3])], // tensor("B", &[2])],
        vec![initializer("W", data_w)], // initializer("B", data_b)],
        vec![node(
            vec!["X", "W"], // "B"],
            vec!["Y"],
            "conv",
            "Conv",
            vec![
                attribute("kernel_shape", vec![3, 3]),
                attribute("strides", vec![1, 1]),
                attribute("pads", vec![1, 1, 1, 1]),
            ],
        )],
    ));

    let session =
        pollster::block_on(wonnx::Session::from_model(conv_model)).expect("Session did not create");
    let mut result = pollster::block_on(session.run(&input_data)).unwrap();
    assert_eq!(
        Vec::<f32>::try_from(result.remove("Y").unwrap()).unwrap(),
        &[
            12.0, 21.0, 27.0, 33.0, 24.0, 33.0, 54.0, 63.0, 72.0, 51.0, 63.0, 99.0, 108.0, 117.0,
            81.0, 93.0, 144.0, 153.0, 162.0, 111.0, 72.0, 111.0, 117.0, 123.0, 84.0, 12.0, 21.0,
            27.0, 33.0, 24.0, 33.0, 54.0, 63.0, 72.0, 51.0, 63.0, 99.0, 108.0, 117.0, 81.0, 93.0,
            144.0, 153.0, 162.0, 111.0, 72.0, 111.0, 117.0, 123.0, 84.0
        ],
    )
}
```

Now remove the commented out param of tensor `B`, the result should just be the same(as bias is zero). Instead wonnx is giving wrong results.

**Comment by zimond** [comment]
The reason why wonnx is passing onnx test suit is that the tests for `conv` op is not covering bias input

**Comment by zimond** [comment]
This is so confusing... I cannot find where the problem is. The shaders and everything seem correct. Is it about my test case ? 🤨

**Comment by zimond** [comment]
I find it!!! @pixelspark  It's your optimization code specified for conv_kernel_3, however, a critical condition is missing: `op_def.output_shapes[0].dim(1) % 4 == 0`, So this test case has only 2 channels, which will lead to `conv.wgsl` with wrong weight (`input[1]`)

Also currently wonnx lacks dynamic shape inferencing. So in practice this `of_def.output_shapes[0]` could just be empty, which makes this whole optimization goes wrong.

**Comment by zimond** [comment]
The reason why the test is passing without bias, is that the optimization requires `new_inputs.len() > 2`, for normal conv ( x + w) the whole optimization is skipped so the bug is not triggering

**Comment by pixelspark** [comment]
> I find it!!! @pixelspark It's your optimization code specified for conv_kernel_3, however, a critical condition is missing: `op_def.output_shapes[0].dim(1) % 4 == 0`, So this test case has only 2 channels, which will lead to `conv.wgsl` with wrong weight (`input[1]`)

Hm, not sure I wrote this, but anway... we should either remove or fix the optimization if it doesn't work. Feel free to make a PR (@haixuanTao any thoughts?).

> Also currently wonnx lacks dynamic shape inferencing. So in practice this `of_def.output_shapes[0]` could just be empty, which makes this whole optimization goes wrong.

Well that's why we require all dimension information to be set (e.g. by running `onnx-simplifier` on your model first)

**Comment by haixuanTao** [comment]
Isn't the condition in the compiler https://github.com/webonnx/wonnx/blob/master/wonnx/src/compiler.rs#L757 enough to avoid using conv_3 template and force the use of the normal conv kernel? 

I'm not seeing the link with the optimiser?

**Comment by haixuanTao** [comment]
Oh it is with the padding of the convolution 3_x_3. Ok so indeed there is a condition missing.

**Comment by zimond** [comment]
> > I find it!!! @pixelspark It's your optimization code specified for conv_kernel_3, however, a critical condition is missing: `op_def.output_shapes[0].dim(1) % 4 == 0`, So this test case has only 2 channels, which will lead to `conv.wgsl` with wrong weight (`input[1]`)
> 
> Hm, not sure I wrote this, but anway... we should either remove or fix the optimization if it doesn't work. Feel free to make a PR (@haixuanTao any thoughts?).
> 
> > Also currently wonnx lacks dynamic shape inferencing. So in practice this `of_def.output_shapes[0]` could just be empty, which makes this whole optimization goes wrong.
> 
> Well that's why we require all dimension information to be set (e.g. by running `onnx-simplifier` on your model first)

Sorry if this is not your code as I just checked git blame. I can confirm that onnx-simplifier cannot cover every case, obviously my model failed to be assigned with all shape information. So in my opinion shape inferencing is inevitable and we should implement it in wonnx 

By the way after disabling this and broadcasting add, my model is running CenterNet for 1.2s on M1 macbook.

**Comment by haixuanTao** [comment]
Thanks for trying to use wonnx anyway. There is still much work to be done to guarantee the good behaving of wonnx for every case, and any contribution like yours is making the package better. 

Couple questions, can you expand on the reason why onnx-simplifier did not manage to infer your shape and how we could fill that gap?  Is 1.2s the running of everything, or just the running inference which consists of the run method?

**Comment by pixelspark** [comment]
> I can confirm that onnx-simplifier cannot cover every case, obviously my model failed to be assigned with all shape information. So in my opinion shape inferencing is inevitable and we should implement it in wonnx

Onnx-simplifier should be able to fully infer all shapes in a model as long as it has all information requirement (and the model is not ambiguously defined). The issue is that many models allow for e.g. dynamically shaped inputs (at least allow batch size to be set). If you don't specify these when running onnx-simplifier, all shapes that depend on the dynamic shape will remain dynamic as well. 

I agree we should probably implement some (opt in) type inference in wonnx for the simple cases (this should also be relatively easy now that we have the IR in wonnx), but that should be focused at the 'common case' (e.g. of models that allow specifying batch size) rather than edge cases that throw up even onnx-simplfiier.

> By the way after disabling this and broadcasting add, my model is running CenterNet for 1.2s on M1 macbook.

Good to hear that another model can be run on wonnx! (ideally we fix the master branch to support this as well and add it to the list). 1.2s for inference doesn't sound that fast but I have no idea what the inference time would be on e.g. Torch or TensorFlow (I see ~30-674ms [here](https://github.com/xingyizhou/CenterNet/blob/master/readme/MODEL_ZOO.md) using a Titan Xp?).

**Comment by zimond** [comment]
Yes. As centernet is not available on macOS, I cannot get a straightforward comparison. However centernet contains lots of Conv, it’s promising that there’s a large margin for optimization, especially currently I disable kernel3 in order to get correct results

**Comment by zimond** [comment]
> Thanks for trying to use wonnx anyway. There is still much work to be done to guarantee the good behaving of wonnx for every case, and any contribution like yours is making the package better.
> 
> Couple questions, can you expand on the reason why onnx-simplifier did not manage to infer your shape and how we could fill that gap? Is 1.2s the running of everything, or just the running inference which consists of the run method?

Only the inference. I will investigate why onnx simplifier failed to inference shapes next week ( highly doubting it’s the custom operator in centernet)

**Comment by zimond** [comment]
I think at least we could expand the error check and warn/throw error when operator has an empty shape.
